
BASE_URL = '/api/v1'

# Страны
COUNTRY_URL = BASE_URL + '/country'
COUNTRY_MODIFY_URL = '/<int:c_id>'

COUNTRY_GET_ALL_URL = COUNTRY_URL + '/all'
COUNTRY_GET_URL = COUNTRY_URL + '/get' + COUNTRY_MODIFY_URL
COUNTRY_CREATE_URL = COUNTRY_URL + '/create'
COUNTRY_DELETE_URL = COUNTRY_URL + '/delete' + COUNTRY_MODIFY_URL

